Adding work and aboutme section mobile version
ichsansandy/portfolio-microverse pull request #2
Opened 2023-04-25 15:38 UTC by ichsansandy

## Work Section
- Using Grid to adjust the cards
- Using Flexbox for layouting inside cards 

## Aboutme Section
- Using Flexbox both in container also inside cards
- Have issue with the background can't copy from Figma (Only bottom logo included, the top image missing)

2023-04-25 16:17 UTC, Zuhaib042 requested changes
Hi @ichsansandy 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

## Highlights
✅ Correct Github flow
✅ Descriptive PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] Kindly consider writing commit messages in Imperative tense so instead of writing `Removing unused assets`, you can write `Remove unused assets` following best practices.
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 16:17 UTC, Zuhaib042 commented on index.html
> +      <div class="section-container">
- [ ] Kindly consider using `display: grid` in this main container as suggested in the requirements. It is necessary to use both grid and flex in this milestone with the sequence suggested in the requirements below
  -  In order to lay out the elements in "Works" section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

2023-04-25 16:17 UTC, Zuhaib042 commented on index.html
> +              <button class="button card-button white">See project</button>
- [ ] This button is following the styling guidelines when hovering, but it is not following the styling guidelines in the pressed state. you can achieve that using `focus` pseudoclass. kindly have a look at the pressed state guidelines. kindly consider fixing this in all the buttons.
- [ ] Also kindly consider increasing the top and bottom padding in your buttons to make it identical to the figma design which is a requirement.
![qw](https://user-images.githubusercontent.com/96683843/234334910-8010f35d-7ed9-4abb-ba04-f291792c25de.jpg)

2023-04-25 16:17 UTC, Zuhaib042 commented on index.html
> +      <div class="aboutme section-container flex-center flex-column align-center">
- [ ] Kindly consider adding the decoration background image seen in the figma design to make it look similar to the figma design.
your design
![fd](https://user-images.githubusercontent.com/96683843/234336878-30e0412d-e394-45d5-a4d0-e5a784219d7c.jpg)

figma design
![as](https://user-images.githubusercontent.com/96683843/234336714-620bcc5a-79ce-45a4-96f5-046edf2c3b3d.jpg)

2023-04-25 16:17 UTC, Zuhaib042 commented on index.html
> +      <div class="aboutme-box-container section-container">
- [ ] Kindly consider using `ul` for these categories in `About myself` section, then languages, frameworks and skills would be list items `li`. you can take the whole card as a `li`. 
  -  Please use ul and li for categories in "About myself" section. Languages, Frameworks, and Skills should be list items.

2023-04-25 16:30 UTC, ichsansandy commented on index.html
> +      <div class="section-container">
Hi @Zuhaib042 
Kindly could you check line 85 
I already use grid in the main container that contains all of the cards line 85
Thanks for considering

2023-04-25 16:31 UTC, ichsansandy commented on index.html
> +      <div class="aboutme section-container flex-center flex-column align-center">
It has bug that we can't take the background from figma and everyone have issue with it
could you give me advise with this thanks

2023-04-26 02:47 UTC, jmonto55 approved these changes
# STATUS: APPROVED 🟢

Hi @ichsansandy , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![AgreeSealGIF](https://user-images.githubusercontent.com/116701485/232347692-8a213af9-b250-4d2c-a690-7f42d3c630e0.gif)

## Highlights

- Excellent implementation of utility classes like .grid, and .flex ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 03:05 UTC, merged